package proyecto;
// Generated 15-mar-2014 14:16:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AlquilerId generated by hbm2java
 */
public class AlquilerId  implements java.io.Serializable {


     private int idcli;
     private int idpel;
     private int num;
     private Date fechaalq;

    public AlquilerId() {
    }

    public AlquilerId(int idcli, int idpel, int num, Date fechaalq) {
       this.idcli = idcli;
       this.idpel = idpel;
       this.num = num;
       this.fechaalq = fechaalq;
    }
   
    public int getIdcli() {
        return this.idcli;
    }
    
    public void setIdcli(int idcli) {
        this.idcli = idcli;
    }
    public int getIdpel() {
        return this.idpel;
    }
    
    public void setIdpel(int idpel) {
        this.idpel = idpel;
    }
    public int getNum() {
        return this.num;
    }
    
    public void setNum(int num) {
        this.num = num;
    }
    public Date getFechaalq() {
        return this.fechaalq;
    }
    
    public void setFechaalq(Date fechaalq) {
        this.fechaalq = fechaalq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlquilerId) ) return false;
		 AlquilerId castOther = ( AlquilerId ) other; 
         
		 return (this.getIdcli()==castOther.getIdcli())
 && (this.getIdpel()==castOther.getIdpel())
 && (this.getNum()==castOther.getNum())
 && ( (this.getFechaalq()==castOther.getFechaalq()) || ( this.getFechaalq()!=null && castOther.getFechaalq()!=null && this.getFechaalq().equals(castOther.getFechaalq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcli();
         result = 37 * result + this.getIdpel();
         result = 37 * result + this.getNum();
         result = 37 * result + ( getFechaalq() == null ? 0 : this.getFechaalq().hashCode() );
         return result;
   }   


}


