package proyecto;
// Generated 15-mar-2014 14:16:27 by Hibernate Tools 3.2.1.GA



/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int idcli;
     private String nombre;
     private String apellidos;
     private String direccion;
     private String codpostal;
     private String localidad;
     private String provincia;
     private String telefono;
     private String observaciones;

    public Clientes() {
    }

	
    public Clientes(int idcli) {
        this.idcli = idcli;
    }
    public Clientes(int idcli, String nombre, String apellidos, String direccion, String codpostal, String localidad, String provincia, String telefono, String observaciones) {
       this.idcli = idcli;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.codpostal = codpostal;
       this.localidad = localidad;
       this.provincia = provincia;
       this.telefono = telefono;
       this.observaciones = observaciones;
    }
   
    public int getIdcli() {
        return this.idcli;
    }
    
    public void setIdcli(int idcli) {
        this.idcli = idcli;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCodpostal() {
        return this.codpostal;
    }
    
    public void setCodpostal(String codpostal) {
        this.codpostal = codpostal;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


