package proyecto;
// Generated 15-mar-2014 14:16:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas  implements java.io.Serializable {


     private int idpel;
     private String titulo;
     private String director;
     private String actores;
     private String genero;
     private Date fechaestreno;
     private Double valoracion;
     private String descripcion;

    public Peliculas() {
    }

	
    public Peliculas(int idpel) {
        this.idpel = idpel;
    }
    public Peliculas(int idpel, String titulo, String director, String actores, String genero, Date fechaestreno, Double valoracion, String descripcion) {
       this.idpel = idpel;
       this.titulo = titulo;
       this.director = director;
       this.actores = actores;
       this.genero = genero;
       this.fechaestreno = fechaestreno;
       this.valoracion = valoracion;
       this.descripcion = descripcion;
    }
   
    public int getIdpel() {
        return this.idpel;
    }
    
    public void setIdpel(int idpel) {
        this.idpel = idpel;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public String getActores() {
        return this.actores;
    }
    
    public void setActores(String actores) {
        this.actores = actores;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Date getFechaestreno() {
        return this.fechaestreno;
    }
    
    public void setFechaestreno(Date fechaestreno) {
        this.fechaestreno = fechaestreno;
    }
    public Double getValoracion() {
        return this.valoracion;
    }
    
    public void setValoracion(Double valoracion) {
        this.valoracion = valoracion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


