/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;
import ES.ES;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;

import java.util.Iterator;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
/**
 *
 * @author BEA
 */
public class VentanaAlquileres extends javax.swing.JDialog {
    Session session;
    DefaultTableModel modelo = new DefaultTableModel();
    int contador;
    Pattern patronnumerico = Pattern.compile("[0-9]");
    Pattern patrontextual = Pattern.compile("[a-zA-Z]");
    Matcher m1, m2;
    int estadocliente=0;
    int estadopelicula=0;
    Calendar hoy;
    /**
     * Creates new form VentanaAlquileres
     */
    public VentanaAlquileres(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cb1.addItem("Id");
        cb1.addItem("Nombre");
        cb1.setSelectedIndex(0); 
        cb2.addItem("Id");
        cb2.addItem("Titulo");
        hoy=Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        labfecha.setText(""+sdf.format(hoy.getTime()));
        
        session = NewHibernateUtil.getSessionFactory().openSession(); 
        BotonesInactivos();
        datosInactivos();
        inicializarTablaPeliculas();
        cuentaAlquileres(session);
        MostrarPeliculas(session);
    }
    
    public void MostrarPeliculas(Session s){
        Peliculas a= new Peliculas();
        Query q = s.createQuery("from Peliculas");
        Iterator<Peliculas> iter= q.iterate();
        Object[] fila= new Object[3];
        Ejemplares e= new Ejemplares();
        List l= new ArrayList();
        boolean sigue=true;
        int n=1;
        while (iter.hasNext()){
                a= (Peliculas) iter.next();
                int id=a.getIdpel();
                int contejem= cuentaejemplaresid(id,session);
                fila[0]= a.getIdpel();
                fila[1]= a.getTitulo();
                fila[2]= contejem;
                modelo.addRow(fila);
        }    
    }
    public int cuentaejemplaresid(int id,Session s){
        int contador2=0;
        Ejemplares c= new Ejemplares();
        Query q = s.createQuery("from Ejemplares where idpel="+id+" and estado='Disponible'");
        Iterator<Ejemplares> iter= q.iterate();
        while(iter.hasNext()){
            c= (Ejemplares) iter.next();
            contador2=contador2+1;
        }  
        System.out.println("Hay "+contador2+" ejemplares");
        return contador2;
    }
        void limpiarDatos(){
        tid.setText("");
        tnombre.setText("");
        tcliente.setText("");
        tpelicula.setText("");
    }
     public void inicializarTablaPeliculas(){
        tabPeliculas.setModel(modelo);
        modelo.addColumn("ID");
        modelo.addColumn("TITULO");
        modelo.addColumn("DISPONIBLES");
    }
    public void BotonesInactivos(){    
        balquilar.setEnabled(false);
        bcancelar.setEnabled(false);
    }
    public void datosActivos(){
        tid.setEditable(true);
        tnombre.setEditable(true);
        tcliente.setEditable(true);
        tpelicula.setEditable(true);
    }
    public void datosInactivos(){
        tid.setEditable(false);
        tnombre.setEditable(false);
        tcliente.setEditable(true);
        tpelicula.setEditable(true);
    }

    public void cuentaAlquileres(Session s){
        contador=0;
        Alquiler c= new Alquiler();
        Query q = s.createQuery("from Alquiler");
        Iterator<Alquiler> iter= q.iterate();
        while(iter.hasNext()){
            c= (Alquiler) iter.next();
            contador=contador+1;
        }  
        System.out.println("Hay "+contador+" alquileres");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cb1 = new javax.swing.JComboBox();
        tcliente = new javax.swing.JTextField();
        bbuscarcli = new javax.swing.JButton();
        tid = new javax.swing.JTextField();
        tnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPeliculas = new javax.swing.JTable();
        bbuscarpel = new javax.swing.JButton();
        cb2 = new javax.swing.JComboBox();
        tpelicula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bcancelar = new javax.swing.JButton();
        bver = new javax.swing.JButton();
        balquilar = new javax.swing.JButton();
        labfecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Americana XBd BT", 1, 24)); // NOI18N
        jLabel1.setText("ALQUILERES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NUEVO ALQUILER:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bbuscarcli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bbuscarcli.setText("BUSCAR");
        bbuscarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarcliActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        jLabel4.setText("NOMBRE:");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 255));

        tabPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabPeliculas);

        bbuscarpel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bbuscarpel.setText("BUSCAR");
        bbuscarpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarpelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("CLIENTES");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PELICULAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bbuscarcli))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel5)))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tpelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bbuscarpel)))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbuscarcli))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbuscarpel)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 780, 240));

        bcancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bcancelar.setText("CANCELAR");
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });
        jPanel1.add(bcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        bver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bver.setText("VER ALQUILERES");
        bver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bverActionPerformed(evt);
            }
        });
        jPanel1.add(bver, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        balquilar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        balquilar.setText("ALQUILAR");
        balquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balquilarActionPerformed(evt);
            }
        });
        jPanel1.add(balquilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        labfecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labfecha.setText("jLabel7");
        jPanel1.add(labfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("FECHA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbuscarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarcliActionPerformed
        // TODO add your handling code here:
        bcancelar.setEnabled(true);
        balquilar.setEnabled(true);
        estadocliente=1;
        int n= cb1.getSelectedIndex();
        Boolean sigue=true;
        Clientes aux= new Clientes();
        
        if (n==0){      //Busca por id
            m1 = patronnumerico.matcher(tcliente.getText());
            if (m1.find()){     // Si es un dato numerico
                aux = (Clientes)session.get(Clientes.class, Integer.parseInt(tcliente.getText()));
                    if (aux==null){
                        //sigue=true;
                        tcliente.setText("");
                        JOptionPane.showMessageDialog(rootPane, "El cliente no existe");
                    }
                    else{       
                        //sigue=false;                    
                        tid.setText(""+aux.getIdcli());
                        tnombre.setText(aux.getNombre());
                        
                    }
            }else if (!m1.find()){
                tcliente.setText("");
                JOptionPane.showMessageDialog(rootPane, "Debe introducir un valor numerico si busca por ID");
            }            
        }
        if (n==1){      //Busca por nombre
            String nombre= tcliente.getText();
            m1 = patrontextual.matcher(nombre);
            
            if (m1.find()){
                for (int i=1; i<=contador; i++){
                    aux = (Clientes)session.get(Clientes.class, i);
                    String clinom= aux.getNombre();
                    if (clinom.compareToIgnoreCase(nombre)==0){
                        sigue=false;                   
                        tid.setText(""+aux.getIdcli());
                        tnombre.setText(aux.getNombre());
                        
                    }
                    else{         
                        sigue=true;
                        tcliente.setText("");
                        
                    }
                }
                if (sigue){
                    JOptionPane.showMessageDialog(rootPane, "No existe "+nombre);
                }
            }else if (!m1.find()){
                tcliente.setText("");
                JOptionPane.showMessageDialog(rootPane, "Debe introducir caracteres alfabeticos si busca por nombre");
            }
        }         

    }//GEN-LAST:event_bbuscarcliActionPerformed

    private void bbuscarpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarpelActionPerformed
        // TODO add your handling code here:
        limpiarTablaPeliculas();
        int n= cb2.getSelectedIndex();
        Peliculas a= new Peliculas();
        Query q=null;
        boolean sigue=true;
        if (n==0){      // buscar por id
            m1 = patronnumerico.matcher(tpelicula.getText());
            if (m1.find()){
                q = session.createQuery("from Peliculas where idpel="+tpelicula.getText());
                Iterator<Peliculas> iter= q.iterate();
                Object[] fila= new Object[3];
                int i=0;
                if (iter.hasNext()){
                        a= (Peliculas) iter.next();
                        int id=a.getIdpel();
                        int contejem= cuentaejemplaresid(id,session);
                        fila[0]= a.getIdpel();
                        fila[1]= a.getTitulo();
                        fila[2]= contejem;
                        modelo.addRow(fila);
                 }else{
                    JOptionPane.showMessageDialog(rootPane, "No existe ninguna pelicula con ese ID");
                 }
            }else{
                tpelicula.setText("");
                JOptionPane.showMessageDialog(rootPane, "Debe introducir un valor numerico si busca por ID");
            }
            
        }
        if (n==1){      // buscar por Titulo
                String titulo= tpelicula.getText();
                //JOptionPane.showMessageDialog(rootPane, "Busca por titulo");
                for (int i=1; i<=contador; i++){
                    a = (Peliculas)session.get(Peliculas.class, i);
                    String pelnom= a.getTitulo();
                    if (pelnom.compareToIgnoreCase(titulo)==0){
                        sigue=false;                   
                        Object[] fila= new Object[3];
                        int id=a.getIdpel();
                        int contejem= cuentaejemplaresid(id,session);
                        fila[0]= a.getIdpel();
                        fila[1]= a.getTitulo();
                        fila[2]= contejem;
                        modelo.addRow(fila);
                        i=contador+1;
                    }
                    else{         
                        sigue=true;
                        tpelicula.setText("");
                    }
                }
                if (sigue){
                    JOptionPane.showMessageDialog(rootPane, "No existe ninguna pelicula con ese título");
                }
        }
    }//GEN-LAST:event_bbuscarpelActionPerformed

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
        limpiarTablaPeliculas();
    }//GEN-LAST:event_bcancelarActionPerformed

    private void balquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balquilarActionPerformed
        // TODO add your handling code here:
        int indice=tabPeliculas.getSelectedRow();
        Query q=null;
        if (indice==-1){
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un elemento de la tabla");
        }
        else{
            if (estadocliente==1){
                try{
                    SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
                    java.util.Date fecha = null;
                    try {
                        fecha = formatoDelTexto.parse(labfecha.getText());
                    } catch (ParseException ex) {
                        ex.printStackTrace();
                    }
                    Ejemplares e=new Ejemplares();
                     EjemplaresId ei= new EjemplaresId();
                     int n=0;
                    int id=(Integer)tabPeliculas.getValueAt(indice, 0);
                    q = session.createQuery("from Ejemplares where idpel="+id+ " and estado='Disponible'");
                    Iterator<Ejemplares> iter= q.iterate();
                    if (iter.hasNext()){
                        e= (Ejemplares)iter.next();
                        ei= e.getId();
                        n= ei.getNum();
                        e.setEstado("Alquilada");
                    }
                    Alquiler a2= new Alquiler(new AlquilerId(Integer.parseInt(tid.getText()),id, n,fecha));
                    session.beginTransaction();
                    session.save(a2);
                    session.getTransaction().commit();

                    JOptionPane.showMessageDialog(rootPane, "Alquiler introducido correctamente");
                }catch(Exception e){
                    System.out.println(e.toString());
                }       
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe elegir un cliente");
            }
        }
    }//GEN-LAST:event_balquilarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bverActionPerformed
        // TODO add your handling code here:
        TodAlquileres ta= new TodAlquileres(this,true);
        ta.setVisible(true);
    }//GEN-LAST:event_bverActionPerformed
     // -------------- LIMPIAR LA TABLA ---------------------------------
    void limpiarTablaPeliculas(){
        while (tabPeliculas.getRowCount()!=0){
           ((DefaultTableModel)tabPeliculas.getModel()).removeRow(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaAlquileres dialog = new VentanaAlquileres(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balquilar;
    private javax.swing.JButton bbuscarcli;
    private javax.swing.JButton bbuscarpel;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton bver;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labfecha;
    private javax.swing.JTable tabPeliculas;
    private javax.swing.JTextField tcliente;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tnombre;
    private javax.swing.JTextField tpelicula;
    // End of variables declaration//GEN-END:variables
}
